### ISSUE TITLE
Interruption inopinée programme ?

### ISSUE THREAD

**Issue by navjul** [Aymkdn/assistant-freebox#14]
Bonjour,

Y a t'il des problèmes connus avec la dernière version du programme ?

Mon contexte est le suivant :  

> jul@ubuntu:~/assistant-plungins/assistant-plugins$ uname -a && node -v && npm -v
Linux ubuntu 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
v10.9.0
6.4.0

L'Ubuntu est une 18.04.1 LTS server toute fraîche.

Le log  de l'erreur :  

>[assistant-freebox] Commande « off » exécutée
events.js:167
      throw er; // Unhandled 'error' event
      ^
>
>Error: Device timeout
    at fn.ontimeout (/home/jul/assistant-plungins/assistant-plugins/node_modules/castv2-client/lib/senders/platform.js:56:26)
    at Object.onceWrapper (events.js:273:13)
    at fn.emit (events.js:182:13)
    at Timeout.ontimeout [as _onTimeout] (/home/jul/assistant-plungins/assistant-plugins/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10)
    at ontimeout (timers.js:424:11)
    at tryOnTimeout (timers.js:288:5)
    at listOnTimeout (timers.js:251:5)
    at Timer.processTimers (timers.js:211:10)
Emitted 'error' event at:
    at fn.ontimeout (/home/jul/assistant-plungins/assistant-plugins/node_modules/castv2-client/lib/senders/platform.js:56:12)
    at Object.onceWrapper (events.js:273:13)
    [... lines matching original stack trace ...]
    at Timer.processTimers (timers.js:211:10)

J'ai éteint la freebox avec succès, suis allé dormir et ce matin cela ne fonctionnait plus.

En passant, comment faire pour faire tourner la commande node index.js en tâche de fond ? actuellement cela me monopolise une console / terminal.

Merci.

**Comment by Aymkdn** [comment]
Et quand tu le relances, tu as un message d'erreur ? Car là tu m'as montré comment il a planté. Il est possible qu'il y ait eu un problème sur ton réseau durant la nuit.

Concernant la mise en tâche de fond : https://aymkdn.github.io/assistant-plugins/#lancer-le-programme-au-d-marrage-et-en-arri-re-plan

**Comment by navjul** [comment]
Non, aucune erreur à la relance. Je vais suivre ton lien pour le faire tourner en arrière plan et on verra si ça le refait ou pas. 

Merci

**Comment by Aymkdn** [comment]
Je ferme l'issue donc.
